### ISSUE TITLE
工信部放出新电信网码号：联通获得167号段 电信获得191号段

### ISSUE THREAD

**Issue by zhwxp** [VincentSit/ChinaMobilePhoneNumberRegex#11]
相关新闻链接
https://tech.sina.com.cn/roll/2018-07-27/doc-ihfvkitx5270210.shtml

[wiki](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%86%85%E5%9C%B0%E7%A7%BB%E5%8A%A8%E7%BB%88%E7%AB%AF%E9%80%9A%E8%AE%AF%E5%8F%B7%E6%AE%B5)上已经更新了，希望能增加新号段支持，谢谢！

**Comment by VincentSit** [comment]
年底了项目忙，有点迟了，不好意思。已经更新了，谢谢提醒。
