### ISSUE TITLE
在awk中无法匹配

### ISSUE THREAD

**Issue by mjl371** [VincentSit/ChinaMobilePhoneNumberRegex#16]
在Linux awk 命令中无法匹配

**Comment by VincentSit** [comment]
Hi @mjl371，这还是语法兼容问题，这些正则主要是面向编程语言的，编程语言大多数都是兼容 PCRE 的。

Linux 内置的那些工具属于 POSIX 流派，又分 BRE（grep、sed 等）、GNU BRE（GNU grep、GNU sed 等）、ERE（egrep、awk 等）以及 GNU ERE（grep –E、GNU awk 等）。

我下午会尽量适配一下。如果方便的话，麻烦您给出一个例子，包含您使用的 awk 语句和需要匹配的内容，尽量精简。

**Comment by mjl371** [comment]
> Hi @mjl371，这还是语法兼容问题，这些正则主要是面向编程语言的，编程语言大多数都是兼容 PCRE 的。
> 
> Linux 内置的那些工具属于 POSIX 流派，又分 BRE（grep、sed 等）、GNU BRE（GNU grep、GNU sed 等）、ERE（egrep、awk 等）以及 GNU ERE（grep –E、GNU awk 等）。
> 
> 我下午会尽量适配一下。如果方便的话，麻烦您给出一个例子，包含您使用的 awk 语句和需要匹配的内容，尽量精简。

感谢科普，既然语法这么多种就不麻烦你重新适配了。建议将这段说明加入reademe，可以close了。谢谢

**Comment by mjl371** [comment]
linux下可以使用 grep -P 来兼容 PCRE 正则

**Comment by VincentSit** [comment]
@mjl371 抱歉回复晚了，对我来说，每一个 star 都是一份责任，我要为你们给的 star 负责，有需求我会尽量满足。我在 #17 做了兼容 ，你可以看看，没有问题我就合并了。

**Comment by mjl371** [comment]
> @mjl371 抱歉回复晚了，对我来说，每一个 star 都是一份责任，我要为你们给的 star 负责，有需求我会尽量满足。我在 #17 做了兼容 ，你可以看看，没有问题我就合并了。

简单测试了部分规则（三网手机号），没有问题。再次感谢
