### ISSUE TITLE
缺少小米手机卡170和171的支持

### ISSUE THREAD

**Issue by xuchenchen** [VincentSit/ChinaMobilePhoneNumberRegex#18]
缺少小米手机卡170和171的支持，例如：17076266790，17076266714，17176266714 这种你都不支持但是这些确实存在的手机号

**Comment by VincentSit** [comment]
抱歉回复迟了，这两天休假没看邮件。你说的这些手机号我测了一下都支持的，你能不能提供一些测试代码之类的信息？

![image](https://user-images.githubusercontent.com/4084679/59986676-59467400-966a-11e9-876d-fb08294bf556.png)
