### ISSUE TITLE
匹配所有手机号的那个表达式，不能匹配 19521302521 这种

### ISSUE THREAD

**Issue by ElegantDancer** [VincentSit/ChinaMobilePhoneNumberRegex#22]

**Comment by VincentSit** [comment]
感谢提醒，195 号段确实没有匹配，我稍后会加上，你现在可以先用下面的。

`^(?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[01356789]\d{2}|4(?:0\d|1[0-2]|9\d))|9[1589]\d{2}|6[567]\d{2}|4(?:[14]0\d{3}|[68]\d{4}|[579]\d{2}))\d{6}$`

**Comment by VincentSit** [comment]
支持了，谢谢！
