### ISSUE TITLE
172号段

### ISSUE THREAD

**Issue by KngStr** [VincentSit/ChinaMobilePhoneNumberRegex#25]
今天有个172号段的用户，可以收短信，但咱这个里面好像没有收录
谢谢

**Comment by VincentSit** [comment]
感谢提醒，目前我不知道这个 172 号段到底是不是纯物联网的卡，具不具备电话功能，我把它归在普通电话卡里了。稍后会更新上来。

**Comment by KngStr** [comment]
好的，谢谢
