### ISSUE TITLE
号段的添加和去除

### ISSUE THREAD

**Issue by ketra21** [VincentSit/ChinaMobilePhoneNumberRegex#27]
根据维基百科:[中国内地移动终端通信号段](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E5%86%85%E5%9C%B0%E7%A7%BB%E5%8A%A8%E7%BB%88%E7%AB%AF%E9%80%9A%E8%AE%AF%E5%8F%B7%E6%AE%B5)
1、需要增加的标签：
中国广电：^(?:\+?86)?192\d{8}$

2、需要增加的号段：
中国移动：
195，197号段
中国联通：
171，196号段
中国电信：
190号段

**Comment by VincentSit** [comment]
谢谢提醒。195 / 197 / 171 / 196 / 190 是已经支持的，对于 192 号段，之前有很多不确定的情况所以我没有添加，我这两天抽空加上，谢谢提醒。

**Comment by ketra21** [comment]
规则里表格里确实加了195等，但是正则的匹配里没有哇，比如：
中国移动
^(?:\+?86)?1(?:3(?:4[^9\D]|[5-9]\d)|5[^3-6\D]\d|7[28]\d|8[23478]\d|98\d)\d{7}$，这个表达式这个就不支持195

**Comment by VincentSit** [comment]
谢谢提醒，这是个 bug，忘记更新这个了，今天如果有时间我会修复，最迟明天。

**Comment by VincentSit** [comment]
@ketra21 有空你看下 #28，感觉没问题我就合并了。
