### ISSUE TITLE
正则优化

### ISSUE THREAD

**Issue by gshmu** [VincentSit/ChinaMobilePhoneNumberRegex#3]
http://45.78.38.197/ss/regex/regex.html#21

用了环视

```
^1(?=\d{10}$)(?:[38]|5[^4\D]|70[^4\D])\d+$
```

**Comment by VincentSit** [comment]
Hi @mhohai，非常感谢 PR。

但是 17x 系列条件不够，你需要再完善一下。

[^1(?=\d{10}$)(?:[38]|5[^4\D]|70[^4\D])\d+$](https://regexper.com/#%5E1%28%3F%3D%5Cd%7B10%7D%24%29%28%3F%3A%5B38%5D%7C5%5B%5E4%5CD%5D%7C70%5B%5E4%5CD%5D%29%5Cd%2B%24)

![image](https://cloud.githubusercontent.com/assets/4084679/18414352/fa597ce2-77f6-11e6-8e57-2839f8a52295.png)

**Comment by gshmu** [comment]
感谢，疏忽了。

只想着优化，环视的作用就是加速失败，我下来就更新

**Comment by VincentSit** [comment]
@mhohai 我先关闭这个 issues 了，正则有更新了，建议你关注一下。

**Comment by gshmu** [comment]
:+1:   好的
