### ISSUE TITLE
145/147开头的中国手机号码支持

### ISSUE THREAD

**Issue by yinjs** [VincentSit/ChinaMobilePhoneNumberRegex#32]
麻烦更新一下14开头的手机号的支持，以下信息未验证，仅供参考
https://zhidao.baidu.com/question/553946707.html

**Comment by yinjs** [comment]
提了一个PR: https://github.com/VincentSit/ChinaMobilePhoneNumberRegex/pull/33

**Comment by VincentSit** [comment]
具体是哪个号段没有支持呢？你提的这两个号段已经是支持了。

**Comment by yinjs** [comment]
> 具体是哪个号段没有支持呢？你提的这两个号段已经是支持了。

145(联通)和147(移动) ，原先好像不支持的，你看一下PR上的改动

**Comment by VincentSit** [comment]
支持的。高频使用的在左侧，14 之类的在尾部。
![image](https://user-images.githubusercontent.com/4084679/103884262-4ba3f280-5119-11eb-9bb6-ab1e559d5838.png)

**Comment by yinjs** [comment]
例如这个正则 手机卡 - 匹配所有 这个正则返回false
`/^(?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[235-8]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|66\d{2})\d{6}$/.test('14512345678')`

**Comment by yinjs** [comment]
> 支持的。高频使用的在左侧，14 之类的在尾部。
> ![image](https://user-images.githubusercontent.com/4084679/103884262-4ba3f280-5119-11eb-9bb6-ab1e559d5838.png)

增加145/147之后的正则可以返回true
`/^(?:\+?86)?1(?:3\d{3}|4[57]\d{2}|5[^4\D]\d{2}|8\d{3}|7(?:[235-8]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|66\d{2})\d{6}$/.test('14512345678')`

**Comment by yinjs** [comment]
懂了，是在后面，但是好像不能识别

**Comment by VincentSit** [comment]
你可能理解错了这个分类。这个项目里的号码卡是分为手机卡、数据卡和上网卡，你那个 145 是属于上网卡的，手机卡的正则不匹配是正常的。你可以用[这个正则](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex/blob/master/README-CN.md#%E5%8C%B9%E9%85%8D%E6%89%80%E6%9C%89%E6%94%AF%E6%8C%81%E7%9F%AD%E4%BF%A1%E5%8A%9F%E8%83%BD%E7%9A%84%E5%8F%B7%E7%A0%81%E6%89%8B%E6%9C%BA%E5%8D%A1--%E4%B8%8A%E7%BD%91%E5%8D%A1)

**Comment by yinjs** [comment]
好的，谢谢

**Comment by VincentSit** [comment]
不客气，有问题再留言。
