### ISSUE TITLE
无法匹配国内147开头的电话号

### ISSUE THREAD

**Issue by zxq142857** [VincentSit/ChinaMobilePhoneNumberRegex#35]
例如：1474343****

**Comment by VincentSit** [comment]
你用的哪个正则，麻烦给出重现步骤。

**Comment by zxq142857** [comment]
用的[匹配所有号码](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex/blob/master/README-CN.md#%E5%8C%B9%E9%85%8D%E6%89%80%E6%9C%89%E5%8F%B7%E7%A0%81%E6%89%8B%E6%9C%BA%E5%8D%A1--%E6%95%B0%E6%8D%AE%E5%8D%A1--%E4%B8%8A%E7%BD%91%E5%8D%A1)

**Comment by zxq142857** [comment]
用的正则是：

> [匹配所有支持短信功能的号码（手机卡 + 上网卡）](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex/blob/master/README-CN.md#%E5%8C%B9%E9%85%8D%E6%89%80%E6%9C%89%E6%94%AF%E6%8C%81%E7%9F%AD%E4%BF%A1%E5%8A%9F%E8%83%BD%E7%9A%84%E5%8F%B7%E7%A0%81%E6%89%8B%E6%9C%BA%E5%8D%A1--%E4%B8%8A%E7%BD%91%E5%8D%A1)

重现步骤：

> https://codepen.io/eiyoyo/pen/YzPXWzQ

**Comment by zxq142857** [comment]
是我使用的问题，147开头的是移动的上网卡号段，我使用的正则是匹配所有手机卡的正则
