### ISSUE TITLE
提交个bug

### ISSUE THREAD

**Issue by ohyeah521** [VincentSit/ChinaMobilePhoneNumberRegex#36]
serialVersionUID = 6576896619930983584L;QQQ+8615838471111 wwww55555

正确的结果应该输出：15838471111

正则匹配输出：['19930983584', '+8615838471111']

**Comment by VincentSit** [comment]
你好，麻烦给一下测试代码。

**Comment by ohyeah521** [comment]
`# @Coding: utf-8

import re

def phone_nummber_extract():
    phone_nummbers = []
    phone_number_n_file = []

    dat="serialVersionUID = 6576896619930983584L;QQQ+8615838471111 wwww55555 dfd8613661118234fdf15887988765dfd    86136666666662222aaa6666666666666666666666234f1157990087651fd157385367891fdf15826789876qqq-15838545678a"
    
    
    # 匹配所有号码（手机卡 + 数据卡 + 上网卡）
    regex = re.compile(r'(?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}')
 


    for tel in regex.findall(dat.lower()):
        tmptel = []
        if (isinstance(tel,tuple)):
            for m in tel:
                if len(m) < 10:
                    continue  # 过滤垃圾
                if m.startswith('86'):
                    tmptel.append(m[2:])
                elif m.startswith('+86'):
                    tmptel.append(m[3:])
                else:
                    tmptel.append(m)
        elif (isinstance(tel,str)):
            if len(tel) < 10:
                continue
            if tel.startswith('86'):
                tmptel.append(tel[2:])
            elif tel.startswith('+86'):
                tmptel.append(tel[3:])
            else:
                tmptel.append(tel)

        print("tel = %s" %  str(tmptel))



if __name__ == '__main__':

    phone_nummber_extract() `

**Comment by zhhony** [comment]
Dear 

这个邮件抄送到了我，可能是因为我关注了这个项目。它这个正则表达式是这样的结构:

 



所以能带出+86的符号，以及带出19930983584。你可能得先向他说明你的dat里面需要依据什么规则来判定。

发件人: ***@***.*** ***@***.***> 代表 ohyeah521
发送时间: 2022年10月1日 8:17
收件人: VincentSit/ChinaMobilePhoneNumberRegex ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

`


@Coding <https://github.com/Coding> : utf-8


import re

def phone_nummber_extract():
phone_nummbers = []
phone_number_n_file = []

dat="serialVersionUID = 6576896619930983584L;QQQ+8615838471111 wwww55555 dfd8613661118234fdf15887988765dfd    86136666666662222aaa6666666666666666666666234f1157990087651fd157385367891fdf15826789876qqq-15838545678a"
 
 
 
 
 
# 匹配所有号码（手机卡 + 数据卡 + 上网卡）
 
regex = re.compile(r'(?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}')
 
 
 
 
 
 
 
for tel in regex.findall(dat.lower()):
 
    tmptel = []
 
    if (isinstance(tel,tuple)):
 
        for m in tel:
 
            if len(m) < 10:
 
                continue  # 过滤垃圾
 
            if m.startswith('86'):
 
                tmptel.append(m[2:])
 
            elif m.startswith('+86'):
 
                tmptel.append(m[3:])
 
            else:
 
                tmptel.append(m)
 
    elif (isinstance(tel,str)):
 
        if len(tel) < 10:
 
            continue
 
        if tel.startswith('86'):
 
            tmptel.append(tel[2:])
 
        elif tel.startswith('+86'):
 
            tmptel.append(tel[3:])
 
        else:
 
            tmptel.append(tel)
 
 
 
    print("tel = %s" %  str(tmptel))
 

if name == 'main':

phone_nummber_extract() 
 

`

**Comment by zhhony** [comment]
***@***.*** 将撤回邮件“[VincentSit/ChinaMobilePhoneNumberRegex] 提交个
bug (Issue #36)”。

**Comment by ohyeah521** [comment]
@zhhony  这个正则错误的把serialVersionUID = 6576896619930983584L中的内容当作手机号检测出来了，从字面意思可以看出，这是一个uid的值。我不知道正则表达式能否做个限定，手机号1*  前面只能是数字86，否则前面就不能为数字，这样应该就可以把这个误检给排除掉，但是我不知道这样复杂的正则表达式该怎么写^_^

**Comment by BBOOXX** [comment]
> @zhhony 这个正则错误的把serialVersionUID = 6576896619930983584L中的内容当作手机号检测出来了，从字面意思可以看出，这是一个uid的值。我不知道正则表达式能否做个限定，手机号1* 前面只能是数字86，否则前面就不能为数字，这样应该就可以把这个误检给排除掉，但是我不知道这样复杂的正则表达式该怎么写^_^

原本的 ^ 限定被你去掉了, 如果你只想匹配+86开头的手机号, 把 (?:\+?86)?  这里最后的这个问号去掉即可满足你的需求

**Comment by ohyeah521** [comment]
@BBOOXX  因为我是做数据清洗，手机号不是在一行的起始位置，所以不能用^。这个手机号可能是在文中的任何一个位置

**Comment by VincentSit** [comment]
@ohyeah521 这个正则本意是为了测试一个给定的号码是不是一个符合规则的手机号码，没考虑到你这种场景。你可以说出你的具体需求，我给你写一个。

**Comment by ohyeah521** [comment]
> 手机号1* 前面只能是数字86，否则前面就不能为数字，这样应该就可以把这个误检给排除掉，但是我不知道这样复杂的正则表达式该怎么写

我的需求就是从大量文本中提取真正的手机号，类似测试代码中的哪些，手机号1* 前面只能是数字86，否则前面就不能为数字，结尾不能是数字
例如：XXXX代表任意字符串
XXXX12313812345678XXXX 这不是一个手机号
XXXX8613811529696XXXX  这是一个手机号
XXXX+8613811529696XXXX  这是一个手机号
XXXX8613811529696testXXXX  这是一个手机号
XXXX8613811529696123123123XXXX  这不是一个手机号
XXXXtest13811529696XXXX  这是一个手机号

**Comment by VincentSit** [comment]
@ohyeah521 这是你要的效果吗?

`[^\d](?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}[^\d]`

**Comment by ohyeah521** [comment]
> @ohyeah521 这是你要的效果吗?
> 
> `[^\d](?:\+?86)?1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}[^\d]`

这个规则执行上面的python代码输出内容如下：
tel = ['q+8615838471111 ']
tel = ['d8613661118234f']
tel = ['f15887988765d']
tel = ['f15826789876q']
tel = ['-15838545678a']

**Comment by zhhony** [comment]
如果手机号前面肯定有86或者+86，也许可以改成如下形式：

 

(?<=\+)?(?<=86)1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}

 

他会把形如+8615838471111这样以+86开头的，以及8613661118234、8613666666666这样以86开头的匹配出来。这个形式会自动把86和+86从输出的结果里删掉，我看到你后面还有专门来删除+86的代码段，这时候就不需要了。

 

发件人: ***@***.*** ***@***.***> 代表 ohyeah521
发送时间: 2022年10月2日 22:29
收件人: VincentSit/ChinaMobilePhoneNumberRegex ***@***.***>
抄送: 大尾巴鱼 ***@***.***>; Mention ***@***.***>
主题: Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

@zhhony <https://github.com/zhhony>  这个正则错误的把serialVersionUID = 6576896619930983584L中的内容当作手机号检测出来了，从字面意思可以看出，这是一个uid的值。我不知道正则表达式能否做个限定，手机号1* 前面只能是数字86，否则前面就不能为数字，这样应该就可以把这个误检给排除掉，但是我不知道这样复杂的正则表达式该怎么写^_^

**Comment by ohyeah521** [comment]
@zhhony   
(?<=\+)?(?<=86)1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}

这条规则很好，但是还是会由一个问题，就是末尾是一堆数字，这时候就会由误报，上面的代码替换规则后，输出结果如下：

tel = ['15838471111']
tel = ['13661118234']
tel = ['13666666666']         ——这个是误报的
[Finished in 76ms]

**Comment by zhhony** [comment]
13666666666这个其实是一个号码，我打过去显示存在但是停机，如果只是单纯过滤这一个号码倒是有办法。

 

发件人: ***@***.*** ***@***.***> 代表 ohyeah521
发送时间: 2022年10月3日 15:57
收件人: VincentSit/ChinaMobilePhoneNumberRegex ***@***.***>
抄送: 大尾巴鱼 ***@***.***>; Mention ***@***.***>
主题: Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

@zhhony <https://github.com/zhhony> 
(?<=+)?(?<=86)1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}

这条规则很好，但是还是会由一个问题，就是末尾是一堆数字，这时候就会由误报，上面的代码替换规则后，输出结果如下：

tel = ['15838471111']
tel = ['13661118234']
tel = ['13666666666'] ——这个是误报的
[Finished in 76ms]

**Comment by zhhony** [comment]
或者还是逻辑上的问题，就是86开头的不一定就是号码

 

发件人: ***@***.*** ***@***.***> 
发送时间: 2022年10月3日 19:37
收件人: 'VincentSit/ChinaMobilePhoneNumberRegex' ***@***.***>; 'VincentSit/ChinaMobilePhoneNumberRegex' ***@***.***>
抄送: 'Mention' ***@***.***>
主题: 回复: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

13666666666这个其实是一个号码，我打过去显示存在但是停机，如果只是单纯过滤这一个号码倒是有办法。

 

发件人: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 代表 ohyeah521
发送时间: 2022年10月3日 15:57
收件人: VincentSit/ChinaMobilePhoneNumberRegex ***@***.*** ***@***.***> >
抄送: 大尾巴鱼 ***@***.*** ***@***.***> >; Mention ***@***.*** ***@***.***> >
主题: Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

@zhhony <https://github.com/zhhony> 
(?<=+)?(?<=86)1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}

这条规则很好，但是还是会由一个问题，就是末尾是一堆数字，这时候就会由误报，上面的代码替换规则后，输出结果如下：

tel = ['15838471111']
tel = ['13661118234']
tel = ['13666666666'] ——这个是误报的
[Finished in 76ms]

**Comment by ohyeah521** [comment]
> 

它可能是一个号码，但是在我分析的语境中它就不是了，因为我分析的文件中很多一串很长的数字，所以会由大量误报，我就想要提取手机号，它的正则应该满足这些条件：
1、手机号1前面如果是数字，那么只能是数字86，并且86前面不能是数字。
2、手机号1前面不是数字
3、手机号的结尾末尾不能是大写字母 L，
4、手机号的结尾不能是数字信息

**Comment by zhhony** [comment]
它可能是一个号码，但是在我分析的语境中它就不是了，因为我分析的文件中很多一串很长的数字，所以会由大量误报，我就想要提取手机号，它的正则应该满足这些条件：
1、手机号1前面如果是数字，那么只能是数字86，并且86前面不能是数字。
2、手机号1前面如果是不是数字
3、手机号的结尾末尾不能是大写字母 L，
4、手机号的结尾不能是数字信息

 

 

按这个规则进行下去，下面几个是不是就是符合定义的手机号：

 

serialVersionUID = 6576896619930983584L;QQQ+8615838471111 wwww55555 dfd8613661118234fdf15887988765dfd    86136666666662222aaa6666666666666666666666234f1157990087651fd157385367891fdf15826789876qqq-15838545678a

 

如果是这样，那下面这个正则应该是你要的效果：

(?<=(?<=\+86)|(?<=86)|(?<![0-9]))1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}(?![0-9L])

 

 

发件人: ***@***.*** ***@***.***> 代表 ohyeah521
发送时间: 2022年10月3日 19:49
收件人: VincentSit/ChinaMobilePhoneNumberRegex ***@***.***>
抄送: 大尾巴鱼 ***@***.***>; Mention ***@***.***>
主题: Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

 

它可能是一个号码，但是在我分析的语境中它就不是了，因为我分析的文件中很多一串很长的数字，所以会由大量误报，我就想要提取手机号，它的正则应该满足这些条件：
1、手机号1前面如果是数字，那么只能是数字86，并且86前面不能是数字。
2、手机号1前面如果是不是数字
3、手机号的结尾末尾不能是大写字母 L，
4、手机号的结尾不能是数字信息

**Comment by ohyeah521** [comment]
> (?<=(?<=\+86)|(?<=86)|(?<![0-9]))1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}(?![0-9L])

这个规则就是我要的结果，大佬威武

**Comment by ohyeah521** [comment]
在做源码审计的时候，经常会误提取很多非手机号的东西，比如下面的代码：
![1](https://user-images.githubusercontent.com/1449374/193598058-5b26c268-c812-4357-ac79-f1e133e789d7.jpg)

![2](https://user-images.githubusercontent.com/1449374/193598112-dd646cf8-3376-4661-a54d-abc8ea11f7fa.jpg)

![3](https://user-images.githubusercontent.com/1449374/193598142-e0fec299-538b-4021-94b5-ca474fbcb3c1.jpg)

**Comment by ohyeah521** [comment]
@zhhony  不知道为啥，上面的规则，结尾排除大写字母L的未生效，还是会跑出来以L结尾的手机号

(?<=(?<=+86)|(?<=86)|(?<![0-9]))1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}**(?![0-9L])**

**Comment by zhhony** [comment]
哦对了我忘了说了。因为你那个程序会吧所有的字母变成小写。绕过去了发自我的华为手机-------- 原始邮件 --------发件人： ohyeah521 ***@***.***>日期： 2022年10月3日周一 22:13收件人： VincentSit/ChinaMobilePhoneNumberRegex ***@***.***>抄送： 大尾巴鱼 ***@***.***>, Mention ***@***.***>主    题： Re: [VincentSit/ChinaMobilePhoneNumberRegex] 提交个bug (Issue #36)

@zhhony  不知道为啥，上面的规则，结尾排除大写字母L的未生效，还是会跑出来以L结尾的手机号

(?<=(?<=+86)|(?<=86)|(?<![0-9]))1(?:3\d{3}|5[^4\D]\d{2}|8\d{3}|7(?:[0-35-9]\d{2}|4(?:0\d|1[0-2]|9\d))|9[0-35-9]\d{2}|6[2567]\d{2}|4(?:(?:10|4[01])\d{3}|[68]\d{4}|[579]\d{2}))\d{6}(?![0-9L])

**Comment by ohyeah521** [comment]
@zhhony  看到了，确实是这样，没问题了。感谢
