### ISSUE TITLE
多语言单元测试

### ISSUE THREAD

**Issue by ddliu** [VincentSit/ChinaMobilePhoneNumberRegex#6]
能否加上不同语言的单元测试，规则变更后，需要确保有全部覆盖到

**Comment by VincentSit** [comment]
好的，我周末写一下。

**Comment by VincentSit** [comment]
@ddliu 

你好我周末比较忙，抽空写了几个语言的，还没有合并，你可以先看一下。

计划是有下面这些语言的测试：

- [x] JavaScript
- [x] Python
- [x] Ruby
- [x] Java
- [x] PHP
- [ ] Perl
- [ ] Shell
- [ ] Go
- [ ] Objective-C
- [ ] Swift
- [ ] C++

你看看还有没有需要补充的可以提出来。

**Comment by ddliu** [comment]
👍

测试的组织有个建议：几个const和规则列表放到一个配置文件会不会好些，在每个测试文件单独维护的话不好同步更新，另外测试本身说服力也不太够；更进一步，你的README也可以用这个配置文件生成了:)

**Comment by VincentSit** [comment]
@ddliu 谢谢建议，有可能的话希望你能尽一份力吧，我并不打算花太多时间在这个项目上。

**Comment by ddliu** [comment]
ok，最近太忙了，有空了可以给PR

**Comment by VincentSit** [comment]
这几天我会为常用语言做一个第三方库，测试会在每个语言的库里单独做。
